[tools]
node = "22"
bun = "latest"
python = "3.12"
go = "1.23"
ruby = "3.3"
elixir = "latest"

act = "latest"
ansible = "latest"
bat = "latest"
bob = "latest"
cocoapods = "latest"
delta = "latest"
docker-compose = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gemini-cli = "latest"
gh = "latest"
glow = "latest"
gum = "latest"
hugo = "latest"
imagemagick = "latest"
just = "latest"
lazygit = "latest"
lua-language-server = "latest"
mas = "latest"
mc = "latest"
meson = "latest"
pipx = "latest"
railway = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stripe = "latest"
stylua = "latest"
tmux = "latest"
tokei = "latest"
xcodegen = "latest"
yq = "latest"
zoxide = "latest"

"vfox:mise-plugins/vfox-cmake" = "latest"
"go:github.com/maaslalani/cue" = "latest"
"go:github.com/maaslalani/slides" = "latest"
"go:github.com/swaggo/swag/cmd/swag" = "latest"
"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@fsouza/prettierd" = "latest"
"npm:@openai/codex" = "latest"
"npm:@yarnpkg/cli-dist" = "latest"
"npm:gitmoji-cli" = "latest"
"npm:pnpm" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "go"]
