[tools]
node = "22"
bun = "latest"
python = "3.12"
go = "1.23"
ruby = "3.3"
elixir = "latest"

act = "latest"
bob = "latest"
delta = "latest"
eza = "latest"
fd = "latest"
fzf = "latest"
gh = "latest"
glow = "latest"
gum = "latest"
imagemagick = "latest"
lua-language-server = "latest"
mas = { version = "latest", os = ["macos"] }
mc = "latest"
meson = "latest"
pipx = "latest"
ripgrep = "latest"
shellcheck = "latest"
shfmt = "latest"
starship = "latest"
stylua = "latest"
tmux = "latest"
tokei = "latest"
yq = "latest"
zoxide = "latest"

"go:honnef.co/go/tools/cmd/staticcheck" = "latest"
"npm:@yarnpkg/cli-dist" = "latest"
"npm:gitmoji-cli" = "latest"
"github:typst/typst" = "latest"
"github:charmbracelet/vhs" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "python", "ruby", "go"]
