gui:
  # use the mocha catpuccin theme
  theme:
    showIcons: true
    lightTheme: false
    activeBorderColor:
      - "#a6e3a1" # Green
      - bold
    inactiveBorderColor:
      - "#cdd6f4" # Text
    optionsTextColor:
      - "#89b4fa" # Blue
    selectedLineBgColor:
      - "#313244" # Surface0
    selectedRangeBgColor:
      - "#313244" # Surface0
    cherryPickedCommitBgColor:
      - "#94e2d5" # Teal
    cherryPickedCommitFgColor:
      - "#89b4fa" # Blue
    unstagedChangesColor:
      - "#89b4fa" # Blue

customCommands:
  - key: '<c-n>'
    prompts:
      - type: 'menu'
        title: 'Creating new branch. What kind of branch is it?'
        options:
          - name: 'feature'
            value: 'feature'
          - name: 'hotfix'
            value: 'hotfix'
          - name: 'bugfix'
            value: 'bugfix'
          - name: 'chore'
            value: 'chore'
      - type: 'input'
        title: 'What is the new branch name?'
        initialValue: ''
    command: 'git checkout -b {{index .PromptResponses 0}}/{{index .PromptResponses 1}}'
    context: 'localBranches'
    loadingText: 'creating branch'
  - key: 'C'
    command: 'oco'
    context: 'files'
    loadingText: 'auto commit'
    subprocess: true
  - key: 'R'
    command: 'git reset --soft HEAD~1'
    context: 'files'
    loadingText: 'undo last commit'
  - key: '<f1>'
    command: 'git reset --soft {{.CheckedOutBranch.UpstreamRemote}}'
    context: 'files'
    prompts:
      - type: 'confirm'
        title: 'Confirm:'
        body: 'Are you sure you want to reset HEAD to {{.CheckedOutBranch.UpstreamRemote}}?'
