animation: true
animation_type: spectrum
sidebar_position: left
decorations: true
window_corner_radius: 0.0
default_folder: /Users/fangafunk/Musa
show_status_bar: false
primary_color: '#3F9D79'
sidebar_width: 500.0
ui_sounds_enabled: true
ui_sounds_volume: 0.04
startup_sound_enabled: true
