animation: true
animation_type: agbe
sidebar_position: left
decorations: true
window_corner_radius: 0.0
default_folder: ~/Musa
show_status_bar: false
primary_color: '#4CAF50'
window_opacity: 100.0
custom_font: ~/Library/Fonts/GohuFont14NerdFontMono-Regular.ttf
sidebar_width: 473.10938
ui_sounds_enabled: true
ui_sounds_volume: 0.2502924
startup_sound_enabled: true
favorites: []
