#!/bin/bash

function get_absolute_path() {
	if [[ -z "$1" ]]; then
		echo "ERROR : Please provide a path."
		return 1
	fi

	if [[ ! -d "$1" ]]; then
		echo "ERROR : The path '$1' is not a directory."
		return 1
	fi

	local absolute_path=$(readlink -f "$1")

	echo "$absolute_path"
}

function create_clangd_file() {

	if [[ -z "$1" ]]; then
		includes_path=$(pwd)
	fi

	if [[ -f .clangd ]]; then
		echo -n "The file .clangd already exists. Do you want to overwrite it? [Y/n]"
		read answer

		if [[ "$answer" == "" ]]; then
			answer="y"
		fi
		if [[ "$answer" == "Y" ]]; then
			answer="y"
		fi
		if [[ "$answer" != "y" ]]; then
			echo "Canceled."
			return 1
		fi
	fi

	includes_path=$(get_absolute_path $1)

	echo "CompileFlags:" > .clangd
	echo "  Add: -I$includes_path" >>.clangd

	echo "File .clangd created."
}

create_clangd_file $1
