#!/bin/bash

SESSION="$1"

tmux has-session -t $SESSION 3>/dev/null

if [ $? != 0 ]; then
    tmux new-session -d -s $SESSION

    tmux rename-window -t 0 'Code'
    tmux send-keys -t 'Code' 'nvim .' C-m

    tmux new-window -t $SESSION -n 'Shell'

    tmux new-window -t $SESSION -n 'Pingu'
    tmux send-keys -t 'Pingu' 'pingu' C-m
fi

tmux attach -t $SESSION
