#!/bin/bash

# Create a DOT digraph of all hyperlinks in all `*.md` vimwiki files in the current
# directory (non-recursive) that point to existing `*.md` vimwiki files in that directory.
# Do not graph same-page hyperlinks, e.g. `[My Description](#My Header)`.
# Do not graph isolated single pages.
echo "digraph G {"
link1='\[[^]]*\]\(([^#][^)]*)\)' # [My Description](#My Header)
link2='\[\[([^#].*?)\]\]'        # [[My Hyperlink]]
IFS=$'\n'
for from in `find *.md -type f | sort`; do
    to_list=$(perl -pe "s/.*?(\$|$link1|$link2)/\2\3\n/g" "$from" | grep . | sort | uniq)
    for to in $to_list; do
        if [[ -f $to.md ]]; then
            printf '    "%s" -> "%s"\n' $(basename -s .md "$from") $to
        fi
    done
done
echo "}"

