return {
    "lukas-reineke/headlines.nvim",
    dependencies = "nvim-treesitter/nvim-treesitter",
    opts = {},
    config = function()
        require("headlines").setup({
            markdown = {
                headline_highlights = { "Headline" },
                bullet_highlights = {
                    "@text.title.1.marker.markdown",
                    "@text.title.2.marker.markdown",
                    "@text.title.3.marker.markdown",
                    "@text.title.4.marker.markdown",
                    "@text.title.5.marker.markdown",
                    "@text.title.6.marker.markdown",
                },
                bullets = { "✿", "✱", "✲", "◉", "○" },
                codeblock_highlight = "CodeBlock",
                dash_highlight = "Dash",
                dash_string = "-",
                quote_highlight = "Quote",
                quote_string = "┃",
                fat_headlines = true,
                fat_headline_upper_string = "▃",
                -- fat_headline_lower_string = "🬂",
                fat_headline_lower_string = "⣿",
            },
            rmd = {
                treesitter_language = "markdown",
                headline_highlights = { "Headline" },
                bullet_highlights = {
                    "@text.title.1.marker.markdown",
                    "@text.title.2.marker.markdown",
                    "@text.title.3.marker.markdown",
                    "@text.title.4.marker.markdown",
                    "@text.title.5.marker.markdown",
                    "@text.title.6.marker.markdown",
                },
                bullets = { "✿", "✱", "✲", "◉", "○" },
                codeblock_highlight = "CodeBlock",
                dash_highlight = "Dash",
                dash_string = "-",
                quote_highlight = "Quote",
                quote_string = "┃",
                fat_headlines = true,
                fat_headline_upper_string = "▃",
                fat_headline_lower_string = "⣿",
            },
            norg = {
                headline_highlights = { "Headline" },
                bullet_highlights = {
                    "@neorg.headings.1.prefix",
                    "@neorg.headings.2.prefix",
                    "@neorg.headings.3.prefix",
                    "@neorg.headings.4.prefix",
                    "@neorg.headings.5.prefix",
                    "@neorg.headings.6.prefix",
                },
                bullets = { "✿", "✱", "✲", "◉", "○" },
                codeblock_highlight = "CodeBlock",
                dash_highlight = "Dash",
                dash_string = "-",
                doubledash_highlight = "DoubleDash",
                doubledash_string = "=",
                quote_highlight = "Quote",
                quote_string = "┃",
                fat_headlines = true,
                fat_headline_upper_string = "▃",
                fat_headline_lower_string = "⣿",
            },
            org = {
                headline_highlights = { "Headline" },
                bullet_highlights = {
                    "@org.headline.level1",
                    "@org.headline.level2",
                    "@org.headline.level3",
                    "@org.headline.level4",
                    "@org.headline.level5",
                    "@org.headline.level6",
                    "@org.headline.level7",
                    "@org.headline.level8",
                },
                bullets = { "✿", "✱", "✲", "◉", "○" },
                codeblock_highlight = "CodeBlock",
                dash_highlight = "Dash",
                dash_string = "-",
                quote_highlight = "Quote",
                quote_string = "┃",
                fat_headlines = true,
                fat_headline_upper_string = "▃",
                fat_headline_lower_string = "⣿",
            },
        })
    end,
}
